import Head from 'next/head'
import Link from "next/link";
import {useKeepAlive} from 'next-easy-keepalive';

export default function Home() {
  const {useMemState, useNotBackEffect} = useKeepAlive('Home');

  const [list, setList] = useMemState<number[]>([], 'list');

  const makeList = () => {
    setTimeout(() => {
      const arr = Array.from({length: 1000}, (_, idx) => idx + 1);
      setList(arr)
    }, 500)
  }

  useNotBackEffect(() => {
    makeList();
  });

  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <ul>
            {list.map(item => <li key={item}>
              <Link href={`/${item}`}>{item} page</Link></li>)}
          </ul>
        </main>
      </>
  )
}
